#pragma config(Sensor, S1,     lsen,           sensorNone)
#pragma config(Sensor, S2,     rsen,           sensorNone)
#pragma config(Motor,  motorB,          rmot,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          lmot,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int D = 56;

int degree(int L)
{
	return 360*L/(3.14 * D);
}

void go(int way, int s)
{
	int l,r;
	if(way == 0)
	{
		 l = 50;
		 r = 50;

	}else if(way == 1)
	{
		 l = 0;
		 r = 50;
	}
	else
	{
		 l = 50;
		 r = 0;
	}

	while(getMotorEncoder(lmot)<degree(s) && getMotorEncoder(rmot)<degree(s))
	{
		setMotorSpeed(lmot, l);
		setMotorSpeed(rmot, r);

	}
	resetMotorEncoder(lmot);
	resetMotorEncoder(rmot);
}

task main()
{

	for(int h = 0; h<4; ++h)
	{
		go(0, 2000);
		go(1, 240);
		go(0, 600);
		go(1, 240);
	}
}
